name: "Deploy to aws"

# Trigger the workflow from the github ui
on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: "Setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install

      - name: "Run the tests"
        run: npm test
      - name: "pm2 install"
        run: npm install pm2 -g

      - name: "Start or Restart App with PM2"
        run: |
          if pm2 list | grep -q "server"; then
            pm2 restart server
          else
            pm2 start src/index.js --name server
          fi

      - name: "Save PM2 process list"
        run: pm2 save

      - name: "Deploy to aws"
        run: pm2 save
